# Generated by Django 5.0.7 on 2026-09-03 01:38

import django.db.models.deletion
import permission.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='菜单编码')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(max_length=100, verbose_name='前端路由')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='角色编码')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='permission.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('private', '保密')], max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='个人简介')),
                ('avatar', models.ImageField(blank=True, upload_to=permission.models.avatar_upload_to, verbose_name='头像')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='首次登录必须修改密码')),
                ('token_version', models.PositiveIntegerField(default=1, verbose_name='令牌版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='permission.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
